name: Build Android APK

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: 签出仓库
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 设置 Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 初始化 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 初始化 Rust 工具链
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Flutter 版本
        run: flutter --version

      - name: 还原依赖 (rhttp)
        working-directory: plugins/rhttp
        run: flutter pub get --no-example --enforce-lockfile

      - name: 还原依赖 (PixEz)
        run: flutter pub get --no-example --enforce-lockfile

      - name: 生成代码 (rhttp)
        working-directory: plugins/rhttp
        run: dart run build_runner build --delete-conflicting-outputs

      - name: 生成代码 (PixEz)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: 构建 APK (Release)
        run: flutter build apk --release --no-pub

      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: pixez-flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
